In [29]:
import tensorflow
import keras
import sklearn
from sklearn import linear_model
from sklearn.utils import shuffle
import numpy as np
import pandas as pd
import matplotlib.pyplot as pyplot
import pickle
#read, and prepare data
from matplotlib import style

ModuleNotFoundError: No module named 'sklearn'

In [2]:
df = pd.read_excel("AirQualityUCI.xlsx")
df.head()
print(list(df.columns))
df

['Date', 'Time', 'CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)', 'PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)', 'PT08.S5(O3)', 'T', 'RH', 'AH']

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2004-03-10,18:00:00,2.6,1360.000000,150,11.881723,1045.500000,166.0,1056.250000,113.0,1692.000000,1267.500000,13.600000,48.875001,0.757754
1,2004-03-10,19:00:00,2.0,1292.250000,112,9.397165,954.750000,103.0,1173.750000,92.0,1558.750000,972.250000,13.300000,47.700000,0.725487
2,2004-03-10,20:00:00,2.2,1402.000000,88,8.997817,939.250000,131.0,1140.000000,114.0,1554.500000,1074.000000,11.900000,53.975000,0.750239
3,2004-03-10,21:00:00,2.2,1375.500000,80,9.228796,948.250000,172.0,1092.000000,122.0,1583.750000,1203.250000,11.000000,60.000000,0.786713
4,2004-03-10,22:00:00,1.6,1272.250000,51,6.518224,835.500000,131.0,1205.000000,116.0,1490.000000,1110.000000,11.150000,59.575001,0.788794
5,2004-03-10,23:00:00,1.2,1197.000000,38,4.741012,750.250000,89.0,1336.500000,96.0,1393.000000,949.250000,11.175000,59.175000,0.784772
6,2004-03-11,00:00:00,1.2,1185.000000,31,3.624399,689.500000,62.0,1461.750000,77.0,1332.750000,732.500000,11.325000,56.775000,0.760312
7,2004-03-11,01:00:00,1.0,1136.250000,31,3.326677,672.000000,62.0,1453.250000,76.0,1332.750000,729.500000,10.675000,60.000000,0.770238
8,2004-03-11,02:00:00,0.9,1094.000000,24,2.339416,608.500000,45.0,1579.000000,60.0,1276.000000,619.500000,10.650000,59.674999,0.764819
9,2004-03-11,03:00:00,0.6,1009.750000,19,1.696658,560.750000,-200.0,1705.000000,-200.0,1234.750000,501.250000,10.250000,60.200001,0.751657
10,2004-03-11,04:00:00,-200.0,1011.000000,14,1.293620,526.750000,21.0,1817.500000,34.0,1196.750000,445.250000,10.075000,60.474999,0.746495
11,2004-03-11,05:00:00,0.7,1066.000000,8,1.133431,512.000000,16.0,1918.000000,28.0,1182.000000,421.750000,11.000000,56.175000,0.736560
12,2004-03-11,06:00:00,0.7,1051.750000,16,1.603768,553.250000,34.0,1738.250000,48.0,1221.250000,471.500000,10.450000,58.125000,0.735295
13,2004-03-11,07:00:00,1.1,1144.000000,29,3.243618,667.000000,98.0,1489.750000,82.0,1339.000000,729.750000,10.200000,59.599999,0.741736
14,2004-03-11,08:00:00,2.0,1333.250000,64,8.013773,899.750000,174.0,1136.000000,112.0,1517.000000,1101.500000,10.750000,57.425000,0.740795
15,2004-03-11,09:00:00,2.2,1351.000000,87,9.540643,960.250000,129.0,1079.000000,101.0,1582.750000,1027.750000,10.500000,60.599998,0.769111
16,2004-03-11,10:00:00,1.7,1233.250000,77,6.335782,827.250000,112.0,1218.000000,98.0,1445.750000,859.750000,10.800000,58.350000,0.755183
17,2004-03-11,11:00:00,1.5,1178.750000,43,4.971584,762.000000,95.0,1327.500000,92.0,1361.750000,670.500000,10.500000,57.925000,0.735161
18,2004-03-11,12:00:00,1.6,1236.000000,61,5.216919,774.250000,104.0,1301.250000,95.0,1401.250000,664.000000,9.525000,66.774999,0.795054
19,2004-03-11,13:00:00,1.9,1285.500000,63,7.269933,868.500000,146.0,1162.250000,112.0,1536.750000,799.000000,8.300000,76.425001,0.839268
20,2004-03-11,14:00:00,2.9,1371.000000,164,11.539007,1033.500000,207.0,983.250000,128.0,1730.250000,1036.500000,8.000000,81.150000,0.873589
21,2004-03-11,15:00:00,2.2,1310.000000,79,8.826223,932.500000,184.0,1081.750000,126.0,1646.500000,946.250000,8.325000,79.799999,0.877784
22,2004-03-11,16:00:00,2.2,1291.750000,95,8.301413,911.500000,193.0,1102.500000,131.0,1590.750000,956.750000,9.700000,71.150002,0.856938
23,2004-03-11,17:00:00,2.9,1383.000000,150,11.151581,1019.750000,243.0,1008.000000,135.0,1718.750000,1104.000000,9.775000,67.624998,0.818501
24,2004-03-11,18:00:00,4.8,1580.750000,307,20.799217,1318.500000,281.0,798.500000,151.0,2083.000000,1408.500000,10.350000,64.174999,0.806544
25,2004-03-11,19:00:00,6.9,1775.500000,461,27.359807,1487.750000,383.0,702.250000,172.0,2332.500000,1704.000000,9.650000,69.300001,0.831921
26,2004-03-11,20:00:00,6.1,1640.000000,401,24.017757,1404.000000,351.0,742.750000,165.0,2191.250000,1653.750000,9.650000,67.750000,0.813314
27,2004-03-11,21:00:00,3.9,1312.750000,197,12.779368,1076.250000,240.0,957.250000,136.0,1706.500000,1284.750000,9.125000,63.974999,0.741924
28,2004-03-11,22:00:00,1.5,964.500000,61,4.707072,748.500000,94.0,1325.250000,85.0,1332.500000,821.000000,8.175000,63.400000,0.690484
29,2004-03-11,23:00:00,1.0,912.750000,26,2.645722,629.250000,47.0,1564.500000,53.0,1252.250000,551.750000,8.250000,60.824999,0.665744
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9327,2005-04-03,09:00:00,1.2,1022.250000,-200,4.082095,715.250000,191.9,806.000000,118.0,1004.250000,830.750000,17.825000,30.675000,0.620458
9328,2005-04-03,10:00:00,1.4,970.250000,-200,3.402194,676.500000,166.4,887.500000,113.2,930.500000,612.500000,21.125000,23.725000,0.587528
9329,2005-04-03,11:00:00,1.3,999.750000,-200,5.313402,779.000000,171.3,804.500000,115.0,1000.750000,639.500000,24.000000,19.275000,0.567283
9330,2005-04-03,12:00:00,1.4,996.000000,-200,5.349138,780.750000,177.0,806.000000,123.9,985.250000,630.750000,26.450000,16.450000,0.559414
9331,2005-04-03,13:00:00,1.0,928.000000,-200,3.817080,700.500000,118.7,925.750000,86.4,902.000000,455.500000,28.675000,13.700000,0.530155
9332,2005-04-03,14:00:00,1.0,932.750000,-200,4.201281,721.750000,120.6,898.750000,87.0,889.500000,449.750000,28.475000,13.075000,0.500166
9333,2005-04-03,15:00:00,1.1,956.000000,-200,5.395234,783.000000,141.9,856.750000,100.4,895.750000,515.750000,30.000000,11.075000,0.462436
9334,2005-04-03,16:00:00,1.3,967.500000,-200,6.313819,826.250000,197.3,866.500000,132.0,898.250000,548.000000,29.425000,10.375000,0.419179
9335,2005-04-03,17:00:00,1.4,952.500000,-200,6.101377,816.500000,241.8,871.500000,156.3,891.000000,603.250000,28.875000,9.875000,0.386566
9336,2005-04-03,18:00:00,1.2,1014.666667,-200,4.594689,742.666667,190.1,850.666667,137.9,980.666667,597.333333,22.800001,21.699999,0.594491
9337,2005-04-03,19:00:00,2.7,1248.000000,-200,11.109658,1018.250000,367.4,598.750000,181.3,1289.250000,1167.000000,19.925000,33.050000,0.760784
9338,2005-04-03,20:00:00,2.5,1180.250000,-200,7.868564,893.750000,355.0,636.250000,186.8,1200.250000,1371.750000,17.500000,40.724999,0.807281
9339,2005-04-03,21:00:00,1.5,1101.750000,-200,5.999005,811.750000,235.2,692.750000,157.8,1178.000000,1042.250000,16.450000,46.550000,0.864238
9340,2005-04-03,22:00:00,1.6,1115.500000,-200,5.817660,803.250000,232.7,696.250000,153.2,1173.000000,1055.000000,15.525000,48.975000,0.857933
9341,2005-04-03,23:00:00,1.2,1099.750000,-200,5.106145,768.750000,170.1,721.750000,127.6,1146.750000,1049.000000,14.275000,52.500000,0.849727
9342,2005-04-04,00:00:00,0.9,1012.000000,-200,3.504006,682.500000,117.2,800.750000,93.0,1072.500000,816.250000,14.175000,51.450000,0.827454
9343,2005-04-04,01:00:00,0.6,944.250000,-200,1.931932,579.000000,69.6,924.750000,58.3,1001.750000,598.250000,13.850000,51.150001,0.805778
9344,2005-04-04,02:00:00,0.5,911.750000,-200,1.489323,543.750000,69.0,958.500000,54.6,1002.000000,573.000000,12.100000,56.300000,0.792730
9345,2005-04-04,03:00:00,0.4,887.000000,-200,1.086365,507.500000,61.7,1046.500000,51.3,973.500000,548.750000,11.325000,58.899999,0.788769
9346,2005-04-04,04:00:00,-200.0,864.250000,-200,0.801504,478.250000,52.3,1116.000000,42.5,958.250000,488.750000,11.825000,55.975000,0.774275
9347,2005-04-04,05:00:00,0.5,888.250000,-200,1.307608,528.000000,76.5,1076.500000,53.1,987.000000,577.500000,10.400000,59.875000,0.754964
9348,2005-04-04,06:00:00,1.1,1030.500000,-200,4.359341,730.250000,182.2,760.000000,93.0,1129.000000,905.000000,9.550000,63.150000,0.753129
9349,2005-04-04,07:00:00,4.0,1383.500000,-200,17.364240,1220.750000,593.7,470.250000,154.6,1600.000000,1457.250000,9.675000,61.924999,0.744608
9350,2005-04-04,08:00:00,5.0,1446.000000,-200,22.393233,1361.500000,586.2,414.750000,173.6,1776.500000,1704.500000,13.550000,48.875000,0.755337
9351,2005-04-04,09:00:00,3.9,1296.500000,-200,13.552393,1102.000000,522.7,506.750000,186.5,1375.250000,1582.500000,18.150001,36.275001,0.748652
9352,2005-04-04,10:00:00,3.1,1314.250000,-200,13.529605,1101.250000,471.7,538.500000,189.8,1374.250000,1728.500000,21.850000,29.250000,0.756824
9353,2005-04-04,11:00:00,2.4,1162.500000,-200,11.355157,1027.000000,353.3,603.750000,179.2,1263.500000,1269.000000,24.325000,23.725000,0.711864
9354,2005-04-04,12:00:00,2.4,1142.000000,-200,12.374538,1062.500000,293.0,603.250000,174.7,1240.750000,1092.000000,26.900000,18.350000,0.640649
9355,2005-04-04,13:00:00,2.1,1002.500000,-200,9.547187,960.500000,234.5,701.500000,155.7,1041.000000,769.750000,28.325000,13.550000,0.513866
9356,2005-04-04,14:00:00,2.2,1070.750000,-200,11.932060,1047.250000,265.2,654.000000,167.7,1128.500000,816.000000,28.500000,13.125000,0.502804

In [3]:
df = df.drop(columns = list(df.columns)[-2:], axis = 1)

In [4]:
df = df.dropna()

In [5]:
df.dtypes

Date             datetime64[ns]
Time                     object
CO(GT)                  float64
PT08.S1(CO)             float64
NMHC(GT)                  int64
C6H6(GT)                float64
PT08.S2(NMHC)           float64
NOx(GT)                 float64
PT08.S3(NOx)            float64
NO2(GT)                 float64
PT08.S4(NO2)            float64
PT08.S5(O3)             float64
T                       float64
dtype: object

In [11]:
Data_f = df[['Date', "CO(GT)","NOx(GT)","NO2(GT)","T"]]

In [12]:
df.columns

Index(['Date', 'Time', 'CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)',
       'PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)',
       'PT08.S5(O3)', 'T'],
      dtype='object')

In [19]:
Data_f =Data_f[Data_f > 0]
Data_f= Data_f.dropna()

In [20]:
Data_f

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T
0,2004-03-10,18:00:00,2.6,1360.000000,150.0,11.881723,1045.500000,166.0,1056.25,113.0,1692.000000,1267.50,13.600000
1,2004-03-10,19:00:00,2.0,1292.250000,112.0,9.397165,954.750000,103.0,1173.75,92.0,1558.750000,972.25,13.300000
2,2004-03-10,20:00:00,2.2,1402.000000,88.0,8.997817,939.250000,131.0,1140.00,114.0,1554.500000,1074.00,11.900000
3,2004-03-10,21:00:00,2.2,1375.500000,80.0,9.228796,948.250000,172.0,1092.00,122.0,1583.750000,1203.25,11.000000
4,2004-03-10,22:00:00,1.6,1272.250000,51.0,6.518224,835.500000,131.0,1205.00,116.0,1490.000000,1110.00,11.150000
5,2004-03-10,23:00:00,1.2,1197.000000,38.0,4.741012,750.250000,89.0,1336.50,96.0,1393.000000,949.25,11.175000
6,2004-03-11,00:00:00,1.2,1185.000000,31.0,3.624399,689.500000,62.0,1461.75,77.0,1332.750000,732.50,11.325000
7,2004-03-11,01:00:00,1.0,1136.250000,31.0,3.326677,672.000000,62.0,1453.25,76.0,1332.750000,729.50,10.675000
8,2004-03-11,02:00:00,0.9,1094.000000,24.0,2.339416,608.500000,45.0,1579.00,60.0,1276.000000,619.50,10.650000
11,2004-03-11,05:00:00,0.7,1066.000000,8.0,1.133431,512.000000,16.0,1918.00,28.0,1182.000000,421.75,11.000000
12,2004-03-11,06:00:00,0.7,1051.750000,16.0,1.603768,553.250000,34.0,1738.25,48.0,1221.250000,471.50,10.450000
13,2004-03-11,07:00:00,1.1,1144.000000,29.0,3.243618,667.000000,98.0,1489.75,82.0,1339.000000,729.75,10.200000
14,2004-03-11,08:00:00,2.0,1333.250000,64.0,8.013773,899.750000,174.0,1136.00,112.0,1517.000000,1101.50,10.750000
15,2004-03-11,09:00:00,2.2,1351.000000,87.0,9.540643,960.250000,129.0,1079.00,101.0,1582.750000,1027.75,10.500000
16,2004-03-11,10:00:00,1.7,1233.250000,77.0,6.335782,827.250000,112.0,1218.00,98.0,1445.750000,859.75,10.800000
17,2004-03-11,11:00:00,1.5,1178.750000,43.0,4.971584,762.000000,95.0,1327.50,92.0,1361.750000,670.50,10.500000
18,2004-03-11,12:00:00,1.6,1236.000000,61.0,5.216919,774.250000,104.0,1301.25,95.0,1401.250000,664.00,9.525000
19,2004-03-11,13:00:00,1.9,1285.500000,63.0,7.269933,868.500000,146.0,1162.25,112.0,1536.750000,799.00,8.300000
20,2004-03-11,14:00:00,2.9,1371.000000,164.0,11.539007,1033.500000,207.0,983.25,128.0,1730.250000,1036.50,8.000000
21,2004-03-11,15:00:00,2.2,1310.000000,79.0,8.826223,932.500000,184.0,1081.75,126.0,1646.500000,946.25,8.325000
22,2004-03-11,16:00:00,2.2,1291.750000,95.0,8.301413,911.500000,193.0,1102.50,131.0,1590.750000,956.75,9.700000
23,2004-03-11,17:00:00,2.9,1383.000000,150.0,11.151581,1019.750000,243.0,1008.00,135.0,1718.750000,1104.00,9.775000
24,2004-03-11,18:00:00,4.8,1580.750000,307.0,20.799217,1318.500000,281.0,798.50,151.0,2083.000000,1408.50,10.350000
25,2004-03-11,19:00:00,6.9,1775.500000,461.0,27.359807,1487.750000,383.0,702.25,172.0,2332.500000,1704.00,9.650000
26,2004-03-11,20:00:00,6.1,1640.000000,401.0,24.017757,1404.000000,351.0,742.75,165.0,2191.250000,1653.75,9.650000
27,2004-03-11,21:00:00,3.9,1312.750000,197.0,12.779368,1076.250000,240.0,957.25,136.0,1706.500000,1284.75,9.125000
28,2004-03-11,22:00:00,1.5,964.500000,61.0,4.707072,748.500000,94.0,1325.25,85.0,1332.500000,821.00,8.175000
29,2004-03-11,23:00:00,1.0,912.750000,26.0,2.645722,629.250000,47.0,1564.50,53.0,1252.250000,551.75,8.250000
30,2004-03-12,00:00:00,1.7,1080.250000,55.0,5.854802,805.000000,122.0,1253.50,97.0,1375.000000,815.50,8.325000
31,2004-03-12,01:00:00,1.9,1043.750000,53.0,6.374298,829.000000,133.0,1247.25,110.0,1378.250000,831.50,7.725000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1199,2004-04-29,17:00:00,4.9,1559.750000,651.0,24.779305,1423.500000,247.0,579.00,143.0,2175.500000,1687.50,20.825000
1200,2004-04-29,18:00:00,5.4,1663.500000,657.0,28.633208,1518.500000,271.0,553.25,145.0,2312.250000,1819.50,20.175000
1201,2004-04-29,19:00:00,6.5,1760.666667,830.0,32.582046,1610.333333,332.0,502.00,146.0,2488.333333,2006.00,20.233334
1202,2004-04-29,20:00:00,4.3,1524.000000,435.0,19.238006,1275.000000,245.0,607.75,122.0,2046.250000,1740.25,18.600000
1203,2004-04-29,21:00:00,2.9,1398.250000,209.0,16.289347,1188.500000,180.0,646.00,112.0,1930.750000,1577.00,18.200000
1204,2004-04-29,22:00:00,2.7,1341.500000,202.0,13.666581,1105.750000,156.0,694.00,102.0,1856.000000,1443.00,17.849999
1205,2004-04-29,23:00:00,2.8,1432.750000,174.0,13.605630,1103.750000,172.0,681.00,97.0,1876.250000,1411.25,16.975000
1206,2004-04-30,00:00:00,2.3,1297.250000,170.0,11.123625,1018.750000,137.0,732.75,85.0,1822.750000,1216.50,16.200000
1207,2004-04-30,01:00:00,1.7,1178.750000,116.0,7.635017,884.000000,91.0,830.00,76.0,1696.250000,1086.00,15.725000
1208,2004-04-30,02:00:00,1.2,1096.750000,91.0,5.940075,809.000000,80.0,897.25,74.0,1628.250000,1049.50,15.725000
1211,2004-04-30,05:00:00,0.8,1005.000000,48.0,4.500867,737.750000,68.0,1004.50,66.0,1563.250000,916.50,15.650000
1212,2004-04-30,06:00:00,1.7,1205.750000,111.0,9.254615,949.250000,162.0,818.25,90.0,1771.000000,1115.75,15.925000
1213,2004-04-30,07:00:00,3.0,1457.750000,345.0,18.329768,1249.000000,213.0,662.00,111.0,2033.000000,1379.75,16.550000
1214,2004-04-30,08:00:00,3.4,1405.250000,332.0,19.940394,1294.750000,161.0,638.00,103.0,2064.500000,1377.50,18.725000
1215,2004-04-30,09:00:00,3.3,1381.250000,344.0,16.619513,1198.500000,209.0,684.75,117.0,1969.500000,1364.75,17.575000
1216,2004-04-30,10:00:00,2.7,1314.500000,212.0,12.646267,1071.750000,191.0,735.50,116.0,1833.250000,1273.00,16.299999
1217,2004-04-30,11:00:00,2.6,1332.250000,166.0,12.935403,1081.500000,215.0,706.50,109.0,1889.000000,1241.50,16.050000
1218,2004-04-30,12:00:00,3.2,1361.500000,214.0,14.878243,1144.750000,212.0,673.00,116.0,1972.500000,1294.25,17.250000
1219,2004-04-30,13:00:00,3.4,1398.500000,377.0,17.389585,1221.500000,202.0,642.50,115.0,2060.750000,1413.00,19.350000
1220,2004-04-30,14:00:00,2.6,1310.250000,210.0,15.363921,1160.000000,153.0,694.75,94.0,1939.250000,1224.25,21.400000
1221,2004-04-30,15:00:00,3.4,1399.250000,265.0,16.685885,1200.500000,185.0,699.25,121.0,1971.250000,1317.75,22.700000
1222,2004-04-30,16:00:00,4.0,1523.500000,365.0,17.994017,1239.250000,210.0,643.50,114.0,2138.750000,1403.50,20.900001
1223,2004-04-30,17:00:00,4.5,1487.000000,454.0,19.202728,1274.000000,215.0,640.50,110.0,2132.750000,1470.75,21.025000
1224,2004-04-30,18:00:00,4.2,1479.750000,460.0,20.991142,1323.750000,215.0,622.00,122.0,2162.250000,1623.00,20.775000
1225,2004-04-30,19:00:00,5.7,1625.750000,642.0,26.879758,1476.000000,281.0,555.00,135.0,2355.750000,1786.00,19.800000
1226,2004-04-30,20:00:00,4.4,1449.250000,501.0,19.494597,1282.250000,254.0,625.00,133.0,2099.500000,1568.50,19.075000
1227,2004-04-30,21:00:00,3.1,1362.500000,234.0,15.100351,1151.750000,189.0,683.75,110.0,1951.250000,1494.75,18.200000
1228,2004-04-30,22:00:00,3.0,1371.250000,212.0,14.594739,1135.750000,174.0,689.00,102.0,1926.750000,1471.25,18.075000
1229,2004-04-30,23:00:00,3.1,1406.250000,275.0,13.697100,1106.750000,167.0,718.25,108.0,1871.500000,1383.75,17.700000
1230,2004-05-01,00:00:00,3.5,1424.500000,275.0,15.187992,1154.500000,185.0,709.25,110.0,1935.750000,1788.75,17.775000

In [23]:
Data_f = Data_f.set_index('Date').groupby(pd.Grouper(freq='D')).mean().dropna()

In [26]:
Data_f.shape

(44, 11)

In [ ]:
from matplotlib import plt